---
title: "Mammogram"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(survey)
library(car)
library(jtools)
library(ggthemes)
library(ggstance)
```

Read in the data.
```{r, import, warning = FALSE, message = FALSE}
# read in cancer module data
cancer = read_csv("./data/cancerxx.csv") %>%
  select(HHX, FMX, FPX, WTFA_SA, STRAT_P, PSU_P, REGION, MAMHAD, MAM6YR, 
         RMAM1_MT, RMAM1YR, RMAM1N, RMAM1T, RMAM2, RMAM3A, RMAM3B, MAMPAY, 
         MAMREAS, MDRECMAM, MAMDNBR, MAMABN1, MFOLLOW0, MFOLLO01, MFOLLO02, 
         MFOLLO03, MFOLLO04, MFOLLO05, MNOTFOL1, MAMMODE, MAMCAN1)

# read in adult data
adult = read_csv("./data/samadult.csv") %>%
  select(HHX, FMX, FPX, AUSUALPL, AHCPLROU, AHCPLKND, FLA1AR)

# read in family data
family = read_csv("./data/familyxx.csv") %>%
  select(HHX, FMX, RAT_CAT4, RAT_CAT5)

# read in person data
person = read_csv("./data/personsx.csv") %>%
  select(HHX, FMX, FPX, AGE_P, EDUC1, SEX, NOTCOV, COVER65, COVER65O, LA1AR,
         LCONDRT, LACHRONR, HISCODI3, RACRECI3, COVER, YRSINUS, PLBORN)

# join these data files into one for analysis
mam_dat = cancer %>%
  left_join(adult, by = c("HHX", "FMX", "FPX")) %>%
  left_join(person, by = c("HHX", "FMX", "FPX")) %>%
  left_join(family, by = c("HHX", "FMX")) 
```

Data Manipulation
```{r}
# CREATE VARIABLES FOR ANALYSIS: OUTCOME AND DEMOGRAPHIC

# outcome is having a mammogram in the last 2 years:RMAM3A = 1,2
# create immigration status variable based on PLBORN and YRSINUS
mam_dat = mam_dat %>%
  mutate(mam_2 = if_else(RMAM3A <= 2, 1, 0),
         imm_stat = case_when(YRSINUS < 4 ~ "In U.S. < 10 yrs",
                              YRSINUS == 4 | YRSINUS == 5 ~ "In U.S. >= 10 yrs",
                              PLBORN == 1 ~ "Born in U.S."))

# create the age category
mam_dat = mam_dat %>% 
  mutate(age_cat = case_when(AGE_P >= 25 & AGE_P < 40 ~ "25–39",
                             AGE_P >= 40 & AGE_P < 50 ~ "40–49",
                             AGE_P >= 50 & AGE_P < 65 ~ "50–64",
                             AGE_P >= 65 ~ "65+"))
# create educ category
mam_dat = mam_dat %>% 
  mutate(educ_cat = case_when(EDUC1 < 13 ~ "Less than high school",
                              EDUC1 >= 13 & EDUC1 < 15 ~ "High school",
                              EDUC1 >= 15 & EDUC1 < 18 ~ "Some college",
                              EDUC1 >= 18 & EDUC1 <= 21 ~ "College graduate"))

# create financial category
mam_dat = mam_dat %>% 
  mutate(finc_cat = case_when(RAT_CAT5 <= 7 |  RAT_CAT5 %in% c(15, 16) ~ "<200%",
                              RAT_CAT5 %in% c(8, 9) ~ "200–299%", 
                              RAT_CAT5 %in% c(10, 11) ~ "300–399%",
                              RAT_CAT5 >= 18 & EDUC1 <= 21 ~ "400–499%",
                              RAT_CAT5 == 14  ~">=500%",
                              RAT_CAT5 == 17  ~">=200%, no further detail",
                              RAT_CAT5 %in% c(96, 99) ~ "Unknown"))

# create usual care category
mam_dat = mam_dat %>% 
  mutate(ausualpl_cat  = case_when(AUSUALPL == 2 ~ "No",
                                   AUSUALPL %in% c(1, 3) ~ "Yes",
                                   AUSUALPL %in% c(7, 8, 9) ~ "Other"))
# create coverage status
mam_dat = mam_dat %>% 
  mutate(cover_cat  = case_when(NOTCOV == 1 | COVER == 4 | COVER65 == 6 ~ "None",
                                COVER == 2 | COVER65 %in% 2:4 ~ "Public",
                                COVER %in% c(1, 3) | COVER65 %in% c(1, 5) ~ "Private/Military"))

# create disability variable
mam_dat = mam_dat %>% 
  mutate(lcond_chronic_cat = if_else(LCONDRT == 1, "Yes", "No"))

# create race & ethnic categories
mam_dat = mam_dat %>% 
  mutate(race_cat = case_when(RACRECI3 == 1 ~ "White",
                              RACRECI3 == 2 ~ "Black",
                              RACRECI3 == 3 ~ "Asian",
                              RACRECI3 == 4 ~ "AN/AI"),
         eth_cat = case_when(HISCODI3 == 1 ~ "Hispanic",
                             HISCODI3 == 2 ~ "Non-Hispanic White",
                             HISCODI3 == 3 ~ "Non-Hispanic Black",
                             HISCODI3 == 4 ~ "Non-Hispanic Asian",
                             HISCODI3 == 5 ~ "Non-Hispanic AN/AI"))


```


Survey Design
```{r}
# create domain variable for inclusion criteria
mam_dat = mam_dat %>%
  mutate(domain = if_else(SEX == 2 & AGE_P >= 40, 1, 0))

# create survey design object
des = svydesign(ids = ~PSU_P, strata = ~STRAT_P, weights = ~WTFA_SA, nest = TRUE, data = mam_dat)
```

Tables
```{r, tables}
# percent of women who have had mammogram in the last two years by age

age_pct = svyby(~mam_2, by = ~domain+age_cat, svymean, na.rm = TRUE, 
                design = des, vartype = c("ci", "se"))
age_pct %>% filter(domain == 1) %>% select(-domain, -se) %>% knitr::kable()


# percent of women who have had mammogram by education
edu_pct = svyby(~mam_2, by = ~domain+educ_cat, svymean, na.rm = TRUE, 
                design = des, vartype = c("se", "ci")) %>%
  filter(domain == 1) %>%
  select(-domain, -se)

edu_counts = filter(mam_dat, domain == 1) %>%
  group_by(educ_cat) %>%
  summarise(count = n())

edu_pct = left_join(edu_pct, edu_counts, by = "educ_cat")

edu_pct %>% 
  knitr::kable()

# percent of women who have had mammogram by financial category
finc_pct = svyby(~mam_2, by = ~domain+finc_cat, svymean, na.rm = TRUE, 
                 design = des, vartype = c("se", "ci")) %>%
  filter(domain == 1) %>%
  select(-domain, -se)

finc_counts = filter(mam_dat, domain == 1) %>%
  group_by(finc_cat) %>%
  summarise(count = n())

finc_pct = left_join(finc_pct, finc_counts, by = "finc_cat")

finc_pct %>% knitr::kable()


# percent of women who have had mammogram by usual care category
ausualp_pct = svyby(~mam_2, by = ~domain+ausualpl_cat, svymean, na.rm = TRUE, 
                    design = des, vartype = c("se", "ci")) %>%
  filter(domain == 1) %>%
  select(-domain, -se)

usual_counts = filter(mam_dat, domain == 1) %>%
  group_by(ausualpl_cat) %>%
  summarise(count = n())

ausualp_pct = left_join(ausualp_pct, usual_counts, by = "ausualpl_cat")

ausualp_pct %>% knitr::kable()


# percent of women who have had mammogram by health coverage
cover_pct = svyby(~mam_2, by = ~domain+cover_cat, svymean, na.rm = TRUE, 
                  design = des, vartype = c("se", "ci")) %>%
  filter(domain == 1) %>%
  select(-domain, -se)

cover_counts = filter(mam_dat, domain == 1) %>%
  group_by(cover_cat) %>%
  summarise(count = n())

cover_pct = left_join(cover_pct, cover_counts, by = "cover_cat")

cover_pct %>% knitr::kable()


# percent of women who have had mammogram by chronic conditions
lcond_chronic_pct = svyby(~mam_2, by = ~domain+lcond_chronic_cat, svymean, 
                          na.rm = TRUE, design = des, vartype = c("se", "ci")) %>%
  filter(domain == 1) %>%
  select(-domain, -se)

chronic_counts = filter(mam_dat, domain == 1) %>%
  group_by(lcond_chronic_cat) %>%
  summarise(count = n())

lcond_chronic_pct = left_join(lcond_chronic_pct, chronic_counts, by = "lcond_chronic_cat")

lcond_chronic_pct %>% knitr::kable()


# percent of women who have had mammogram by race
race_pct = svyby(~mam_2, by = ~domain+race_cat, svymean, na.rm = TRUE, 
                 design = des, vartype = c("se", "ci")) %>%
  filter(domain == 1) %>%
  select(-domain, -se)

race_counts = filter(mam_dat, domain == 1) %>%
  group_by(race_cat) %>%
  summarise(count = n())

race_pct = left_join(race_pct, race_counts, by = "race_cat")

race_pct %>% knitr::kable()


# percent of women who have had mammogram by ethnicity
eth_pct = svyby(~mam_2, by = ~domain+eth_cat, svymean, na.rm = TRUE, 
                design = des, vartype = c("se", "ci")) %>%
  filter(domain == 1) %>%
  select(-domain, -se)

eth_counts = filter(mam_dat, domain == 1) %>%
  group_by(eth_cat) %>%
  summarise(count = n())

eth_pct = left_join(eth_pct, eth_counts, by = "eth_cat")

eth_pct %>% knitr::kable()

# percent of women who have had mammogram by immigration status
imm_pct = svyby(~mam_2, by = ~domain+imm_stat, svymean, na.rm = TRUE,
                design = des, vartype = c("se", "ci")) %>%
  filter(domain == 1) %>%
  select(-domain, -se)

imm_counts = filter(mam_dat, domain == 1) %>%
  group_by(imm_stat) %>%
  summarise(count = n())

imm_pct = left_join(imm_pct, imm_counts, by = "imm_stat")

imm_pct %>% knitr::kable()
```


Tables By Age Group 

```{r, age_table}
# percent of women who have had mammogram by education and age 
edu_pct_strat = svyby(~mam_2, by = ~domain + age_cat + educ_cat, svymean, 
                      na.rm = TRUE, design = des, vartype = c("se", "ci"))
edu_tab = edu_pct_strat %>% 
  filter(domain == 1) %>% 
  select(-domain, -se) 

edu_counts2 = filter(mam_dat, domain == 1) %>%
  group_by(age_cat, educ_cat) %>%
  summarise(count = n())

edu_tab = left_join(edu_tab, edu_counts2, by = c("age_cat", "educ_cat"))

edu_tab %>% knitr::kable()


# percent of women who have had mammogram by financial category and age
finc_pct_strat = svyby(~mam_2, by = ~domain + age_cat + finc_cat, svymean, 
                       na.rm = TRUE, design = des, vartype = c("se", "ci"))

finc_tab = finc_pct_strat %>% 
  filter(domain == 1) %>% 
  select(-domain, -se) 

finc_counts2 = filter(mam_dat, domain == 1) %>%
  group_by(age_cat, finc_cat) %>%
  summarise(count = n())

finc_tab = left_join(finc_tab, finc_counts2, by = c("age_cat", "finc_cat"))

finc_tab %>% knitr::kable()


# percent of women who have had mammogram by usual care and age
ausualp_pct_strat = svyby(~mam_2, by = ~domain + age_cat + ausualpl_cat,
                          svymean, na.rm = TRUE, design = des, 
                          vartype = c("se", "ci"))

usual_tab = ausualp_pct_strat %>% 
  filter(domain == 1) %>% 
  select(-domain, -se) 

usual_counts2 = filter(mam_dat, domain == 1) %>%
  group_by(age_cat, ausualpl_cat) %>%
  summarise(count = n())

usual_tab = left_join(usual_tab, usual_counts2, by = c("age_cat", "ausualpl_cat"))

usual_tab %>% knitr::kable()


# percent of women who have had mammogram by health coverage and age
cover_pct_strat = svyby(~mam_2, by = ~domain + age_cat + cover_cat, svymean,
                        na.rm = TRUE, design = des, vartype = c("se", "ci"))

ins_tab = cover_pct_strat %>% 
  filter(domain == 1) %>% 
  select(-domain, -se)

ins_counts2 = filter(mam_dat, domain == 1) %>%
  group_by(age_cat, cover_cat) %>%
  summarise(count = n())

ins_tab = left_join(ins_tab, ins_counts2, by = c("age_cat", "cover_cat"))

ins_tab %>% knitr::kable()



# percent of women who have had mammogram by chronic conditions and age
lcond_chronic_pct_strat = svyby(~mam_2, 
                                by = ~domain + age_cat + lcond_chronic_cat,
                                svymean, na.rm = TRUE, design = des,
                                vartype = c("se", "ci"))

dis_tab = lcond_chronic_pct_strat %>% 
  filter(domain == 1) %>% 
  select(-domain, -se)

dis_counts2 = filter(mam_dat, domain == 1) %>%
  group_by(age_cat, lcond_chronic_cat) %>%
  summarise(count = n())

dis_tab = left_join(dis_tab, dis_counts2, by = c("age_cat", "lcond_chronic_cat"))

dis_tab %>% knitr::kable()


# percent of women who have had mammogram by race and age
race_pct_strat = svyby(~mam_2, by = ~domain + age_cat + race_cat, svymean, 
                       na.rm = TRUE, design = des, vartype = c("se", "ci"))

race_tab = race_pct_strat %>% 
  filter(domain == 1) %>% 
  select(-domain, -se) 

race_counts2 = filter(mam_dat, domain == 1) %>%
  group_by(age_cat, race_cat) %>%
  summarise(count = n())

race_tab = left_join(race_tab, race_counts2, by = c("age_cat", "race_cat"))

race_tab %>% knitr::kable()


# percent of women who have had mammogram by ethnicity and age
eth_pct_strat = svyby(~mam_2, by = ~domain + age_cat + eth_cat, svymean, 
                      na.rm = TRUE, design = des, vartype = c("se", "ci"))

eth_tab = eth_pct_strat %>% 
  filter(domain == 1) %>% 
  select(-domain, -se) 

eth_counts2 = filter(mam_dat, domain == 1) %>%
  group_by(age_cat, eth_cat) %>%
  summarise(count = n())

eth_tab = left_join(eth_tab, eth_counts2, by = c("age_cat", "eth_cat"))

eth_tab %>% knitr::kable()

# percent of women who have had mammogram by immigration and age
imm_pct_strat = svyby(~mam_2, by = ~domain + age_cat + imm_stat, svymean,
                      na.rm = TRUE, design = des, vartype = c("se", "ci"))

imm_tab = imm_pct_strat %>%
  filter(domain == 1) %>%
  select(-domain, -se)

imm_counts2 = filter(mam_dat, domain == 1) %>%
  group_by(age_cat, imm_stat) %>%
  summarise(count = n())

imm_tab = left_join(imm_tab, imm_counts2, by = c("age_cat", "imm_stat"))

imm_tab %>% knitr::kable()

# overall percent of women who have had mammogram
total = svyby(~mam_2, by = ~domain + age_cat, svymean, na.rm = TRUE, 
              design = des, vartype = c("se", "ci"))

tot_tab = total %>% 
  filter(domain == 1) %>% 
  select(-domain, -se) 

tot_counts = filter(mam_dat, domain == 1) %>%
  group_by(age_cat) %>%
  summarise(count = n())

tot_tab = left_join(tot_tab, tot_counts, by = "age_cat")

tot_tab %>% knitr::kable()

all_counts = filter(mam_dat, domain == 1)

tot_pct = svyby(~mam_2, by = ~domain, svymean, na.rm = TRUE, design = des,
                vartype = c("se", "ci")) %>%
  filter(domain == 1) %>%
  select(-domain, -se) %>%
  mutate(age_cat = "40+",
         count = 12483)


```

Combine into paper table

```{r}
# COMBINE TABLES BY AGE WITH TABLES OVERALL

# overall

tot_tab = rbind(tot_pct, tot_tab)

tot_tab2 = tot_tab %>%
  mutate(type = "Total",
         level = "-")

# education
edu_pct2 = edu_pct %>%
  mutate(age_cat = "40+")

edu_tab = rbind(edu_pct2, edu_tab)

# factor levels for presentation
edu_tab2 = edu_tab %>%
  mutate(type = "Education") %>%
  rename(level = educ_cat) %>%
  mutate(level = factor(level, levels = c("Less than high school", "High school", "Some college", "College graduate"))) %>%
  arrange(level)

# financial category
finc_pct2 = finc_pct %>%
  mutate(age_cat = "40+")

finc_tab = rbind(finc_pct2, finc_tab)

# factor levels for presentation
finc_tab2 = finc_tab %>%
  mutate(type = "Family Income Poverty Ratio") %>%
  rename(level = finc_cat) %>%
  mutate(level = factor(level, levels = c("<200%", ">=200%, no further detail", "200–299%", "300–399%", "400–499%", ">=500%", "Unknown"))) %>%
  arrange(level)

# usual care category
ausualp_pct2 = ausualp_pct %>%
  mutate(age_cat = "40+")

usual_tab = rbind(ausualp_pct2, usual_tab)


# factor levels for presentation
usual_tab2 = usual_tab %>%
  mutate(type = "Usual Source of Care") %>%
  rename(level = ausualpl_cat) %>%
  mutate(level = factor(level, levels = c("No", "Yes", "Other"))) %>%
  arrange(level)

# insurance coverage category
cover_pct2 = cover_pct %>%
  mutate(age_cat = "40+")

ins_tab = rbind(cover_pct2, ins_tab)

# factor levels for presentation
ins_tab2 = ins_tab %>%
  mutate(type = "Insurance Type") %>%
  rename(level = cover_cat) %>%
  mutate(level = factor(level, levels = c("None", "Public", "Private/Military"))) %>%
  arrange(level)

# chronic condition category
lcond_chronic_pct2 = lcond_chronic_pct %>%
  mutate(age_cat = "40+")

dis_tab = rbind(lcond_chronic_pct2, dis_tab)

# factor levels for presentation
dis_tab2 = dis_tab %>%
  mutate(type = "Chronic Disability") %>%
  rename(level = lcond_chronic_cat) %>%
  mutate(level = factor(level, levels = c("Yes", "No"))) %>%
  arrange(level)

# ethnic category
eth_pct2 = eth_pct %>%
  mutate(age_cat = "40+")

eth_tab = rbind(eth_pct2, eth_tab)

# factor levels for presentation
eth_tab2 = eth_tab %>%
  mutate(type = "Ethnicity") %>%
  rename(level = eth_cat) %>%
  mutate(level = factor(level, levels = c("Hispanic", "Non-Hispanic White", "Non-Hispanic Black", "Non-Hispanic AN/AI", "Non-Hispanic Asian"))) %>%
  arrange(level)

# race category
race_pct2 = race_pct %>%
  mutate(age_cat = "40+")

race_tab = rbind(race_pct2, race_tab)

# factor levels for presentation
race_tab2 = race_tab %>%
  mutate(type = "Race") %>%
  rename(level = race_cat) %>%
  mutate(level = factor(level, levels = c("White", "Black", "AN/AI", "Asian"))) %>%
  arrange(level)

# immigration category
imm_pct2 = imm_pct %>%
  mutate(age_cat = "40+")

imm_tab = rbind(imm_pct2, imm_tab)

# factor levels for presentation
imm_tab2 = imm_tab %>%
  mutate(type = "Immigration") %>%
  rename(level = imm_stat) %>%
  mutate(level = factor(level, levels = c("In U.S. < 10 yrs", "In U.S. >= 10 yrs", "Born in U.S."))) %>%
  arrange(level)

# create table of percentages of women who have gotten mammograms within the last two years (still need to add CIs)
tab_one = rbind(tot_tab2, edu_tab2, finc_tab2, usual_tab2, ins_tab2, dis_tab2, eth_tab2, race_tab2, imm_tab2) %>%
  mutate(mam_2 = round(mam_2*100, 1),
         ci_l = round(ci_l*100, 1),
         ci_u = round(ci_u*100, 1),
         CI = str_c(ci_l, ", ", ci_u)) %>%
  rename(Percent = mam_2,
         N = count) %>%
  select(-ci_l, -ci_u) %>%
  pivot_wider(names_from = age_cat, values_from = c(N, Percent, CI)) %>%
  janitor::clean_names() %>%
  select(type, level, n_40, percent_40, ci_40, n_40_49, percent_40_49, ci_40_49, n_50_64, percent_50_64, ci_50_64, everything())

# print percentages
tab_one %>% knitr::kable()
```

Barplots of Usual Care and Insurance Coverage

```{r}
# sample size
usual_size = mam_dat %>%
  filter(domain == 1) %>%
  group_by(ausualpl_cat) %>%
  summarise(count = n()) %>%
  filter(ausualpl_cat != "NA")
sum(pull(usual_size, count))

# usual source of care barchart
usual_tab %>%
  filter(age_cat != "40+" & ausualpl_cat != "Other") %>%
  ggplot(aes(x = ausualpl_cat, y = mam_2, fill = ausualpl_cat)) +
  geom_col() +
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.25, 0.5, 0.75, 1)) +
  geom_errorbar(aes(ymin = ci_l, ymax = ci_u)) +
  facet_grid(~age_cat) + ggthemes::theme_few() + ggthemes::scale_fill_few() + theme(legend.position = "none") +
  labs(y = "Percent Had Mammogram, Last 2 Years", x = "Usual Source of Care (Have/Have Not)", title = "N = 12483")

# sample size
ins_size = mam_dat %>%
  filter(domain == 1) %>%
  group_by(cover_cat) %>%
  summarise(count = n()) %>%
  filter(cover_cat != "NA")
sum(pull(ins_size, count))

# insurance type barchart
ins_tab %>%
  filter(age_cat != "40+") %>%
  ggplot(aes(x = cover_cat, y = mam_2, fill = cover_cat)) +
  geom_col() + 
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.25, 0.5, 0.75, 1)) +
  geom_errorbar(aes(ymin = ci_l, ymax = ci_u)) +
  facet_grid(~age_cat) + ggthemes::theme_few() + ggthemes::scale_fill_few() + theme(legend.position = "none") +
  labs(y = "Percent Had Mammogram, Last 2 Years", x = "Type of Insurance Coverage", title = "N = 12436")
```


Models


*collapsing some categories*

```{r}
# make financial status and ethnicity only two levels 
mam_dat2 = mam_dat %>%
  mutate(finc_cat2 = if_else(finc_cat == "<200%", finc_cat,
                             if_else(finc_cat == "Unknown", finc_cat, ">=200%")),
         eth_cat2 = if_else(eth_cat == "Hispanic", eth_cat, "Non-Hispanic"),
         imm_stat2 = if_else(imm_stat == "Born in U.S.", imm_stat, "Immigrated"),
         ausualpl_cat2 = replace(ausualpl_cat, ausualpl_cat == "Other", NA),
         lcond_chronic_cat2 = if_else(lcond_chronic_cat == "Yes", "Yes (Chronic)", lcond_chronic_cat))

# refit the design object
des2 = svydesign(ids = ~PSU_P, strata = ~STRAT_P, weights = ~WTFA_SA, nest = TRUE, data = mam_dat2)


# fit the full model on all categorical variables for the included women
mam2_fit = svyglm(mam_2 ~ as.factor(age_cat) + as.factor(educ_cat) + as.factor(finc_cat2) + as.factor(ausualpl_cat2) + as.factor(cover_cat) + as.factor(lcond_chronic_cat2) + as.factor(race_cat) + as.factor(eth_cat2) + as.factor(imm_stat2), 
       design = des2, subset = domain == 1, family = binomial(link = "logit"))

summary(mam2_fit)
summ(mam2_fit)

# Rao-scott LRT ANOVA

# test significance of full model
regTermTest(mam2_fit,  ~ as.factor(age_cat) + as.factor(educ_cat) + as.factor(finc_cat2) + as.factor(ausualpl_cat2) + as.factor(cover_cat) + as.factor(lcond_chronic_cat2) + as.factor(race_cat) + as.factor(eth_cat2) + as.factor(imm_stat2),
            method = "LRT")

# test significance of individual terms/term groups
regTermTest(mam2_fit, "as.factor(age_cat)", 
            method = "LRT") # sig

regTermTest(mam2_fit, "as.factor(educ_cat)",
            method = "LRT") # sig

regTermTest(mam2_fit, "as.factor(finc_cat2)",
            method = "LRT") # sig

regTermTest(mam2_fit, "as.factor(ausualpl_cat2)",
            method = "LRT") # sig

regTermTest(mam2_fit, "as.factor(cover_cat)",
            method = "LRT") # sig

regTermTest(mam2_fit, "as.factor(lcond_chronic_cat2)",
            method = "LRT") # sig

regTermTest(mam2_fit, "as.factor(race_cat)",
            method = "LRT") # not sig

regTermTest(mam2_fit, "as.factor(eth_cat2)",
            method = "LRT") # sig

regTermTest(mam2_fit, "as.factor(imm_stat2)",
            method = "LRT") # not sig

# fit reduced model with significant predictors
mam2_fit2 = svyglm(mam_2 ~ as.factor(age_cat) + as.factor(educ_cat) + as.factor(finc_cat2) + as.factor(ausualpl_cat2) + as.factor(cover_cat) + as.factor(lcond_chronic_cat2) + as.factor(eth_cat2),
                   design = des2, subset = domain == 1, 
                   family = binomial(link = "logit"))

summary(mam2_fit2)
summ(mam2_fit2) # 0.05-0.20 

# Rao-Scott of full model
regTermTest(mam2_fit2,  ~ as.factor(age_cat) + as.factor(educ_cat) + as.factor(finc_cat2) + as.factor(ausualpl_cat2) + as.factor(cover_cat) + as.factor(lcond_chronic_cat2) + as.factor(eth_cat2))

# single term/term group significance
regTermTest(mam2_fit2, "as.factor(age_cat)",
            method = "LRT") # sig

regTermTest(mam2_fit2, "as.factor(educ_cat)",
            method = "LRT") # sig

regTermTest(mam2_fit2, "as.factor(finc_cat2)",
            method = "LRT") # sig

regTermTest(mam2_fit2, "as.factor(ausualpl_cat2)",
            method = "LRT") # sig

regTermTest(mam2_fit2, "as.factor(cover_cat)",
            method = "LRT") # sig

regTermTest(mam2_fit2, "as.factor(lcond_chronic_cat2)",
            method = "LRT") # sig

regTermTest(mam2_fit2, "as.factor(eth_cat2)",
            method = "LRT") # sig


# give labels to the coefficients to look nicer on the OR graph

coef <- names(coef(mam2_fit2))
coef_new = stringr::str_remove(coef, "^[^_]*_cat[)]")
coef_new = stringr::str_remove(coef_new, "^[^_]*_cat2[)]")
coef_new = stringr::str_remove(coef_new, "^[^_]*_chronic")
coef_new = stringr::str_remove(coef_new, "^*_cat2[)]")
names(coef) <- coef_new
coef1 = coef[-1] # remove intercept 

model_coef = broom::tidy(mam2_fit2, conf.int = TRUE, conf.level = 0.95, exponentiate = TRUE) %>%
  mutate(term = case_when(term == "(Intercept)" ~ "Intercept",
                          term == "as.factor(age_cat)50–64" ~ "50-64 vs <50",
                          term == "as.factor(age_cat)65+" ~ "65+ vs <50",
                          term == "as.factor(educ_cat)High school" ~ "High School Degree vs College Degree",
                          term == "as.factor(educ_cat)Less than high school" ~ "Less than High School vs College Degree",
                          term == "as.factor(educ_cat)Some college" ~ "Some college vs College Degree",
                          term == "as.factor(finc_cat2)>=200%" ~ ">=200% vs <200% Poverty Level",
                          term == "as.factor(ausualpl_cat2)Yes" ~ "Usual Source of Care vs No Usual Source of Care",
                          term == "as.factor(cover_cat)Private/Military" ~ "Private/Military Insurance vs No Insurance",
                          term == "as.factor(cover_cat)Public" ~ "Public Insurance vs No Insurance",
                          term == "as.factor(lcond_chronic_cat2)Yes (Chronic)" ~ "Chronic Condition vs No Chronic Condition",
                          term == "as.factor(eth_cat2)Non-Hispanic" ~ "Non-Hispanic vs Hispanic"))

model_coef %>% knitr::kable()

# plot ORs with CIs
jtools::plot_summs(mam2_fit2, coefs = coef1, exp = TRUE) +
  labs(title = "Mammogram Significant Predictors") 
```


```{r, data_export}
# write out analysis data set

# write_csv(mam_dat2, "C:/Users/court/Documents/Columbia/Fall 2019/Health Surveys/Final Project/mam_analysis.csv")
```

